#!/usr/bin/env python3
"""Blink sequence from a 3x1 mask sheet whose FIRST cell is the finished rest pose.

  blinksheet.py <who> [--stage build|generate|split|all] [--tree ...]

One generation produces the whole blink: open, half-open, closed, drawn side by
side in a single pass so the in-between actually reads as an in-between.
Generated as separate calls, the half state came out barely distinguishable
from open.

The character-pipeline docs record two earlier blink SHEETS that were abandoned:
v1 followed the grid template and drifted in style, v2 followed the plate and
drifted ~14% in scale. Neither had an anchor. Here cell 1 is not a silhouette —
it is the finished rest artwork, stamped by Sprite Studio's own `gridSheet` at
the same geometry as the two silhouettes beside it. The model reproduces it and
matches the other two to it, which is what removes that freedom.

The sheet IS the sequence. Cells are sliced in equal thirds and de-keyed with no
trim, so all three stay on one canvas at one framing — that co-registration is
what the grid template exists to guarantee, and nothing is composited on top.
"""
import argparse
import json
import os
import shutil
import subprocess

from PIL import Image

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SCRIPTS))))
NODE = os.path.join(os.path.expanduser('~'), '.nvm/versions/node/v22.22.0/bin')
CELL = 900
AR = 21 / 9          # the offered ratio nearest a 3x1 of a bust; pad to it exactly
CELLS = ('open', 'half', 'closed')
# Three unique drawings, four steps: the lid passes through half on the way back
# open. Sprite Studio's blink preset cadence, and the same numbers the dragon
# head frames use. Frame 3 is frame 1 again — the repo's banks already reuse
# frames this way (Laurah's talk_short repeats two of its five).
STEPS = (('open', 2600), ('half', 45), ('closed', 70), ('half', 55))

ANCHOR = """

IMPORTANT — CELL 1 IS ALREADY DRAWN. The layout template (Image 2) is not three empty silhouettes: its FIRST cell already contains the finished artwork, and the second and third cells are white silhouettes to be filled. Reproduce cell 1 EXACTLY as it already appears — same drawing, same scale, same position, same colours, same rendering — and treat it as the definitive reference for how cells 2 and 3 must look. Cells 2 and 3 are that identical drawing with ONLY the eyelids lowered: cell 2 half-lowered, cell 3 fully closed. Match cell 1's head size and head position to the pixel; the three cells play as one blink, so any change in scale, framing or style between them is an error. Keep every cell fully inside its own cell with clear margin on all sides — nothing may touch or cross a cell edge. She is BARE-HEADED in every cell.
"""

README = """{who}_blink — After Effects PNG sequence (character-bank sequence)
Generated by blinksheet.py from a 3x1 Sprite Studio mask sheet

Character   : {who}
Sequence    : blink
Files       : {n} PNGs — one per animation frame, {w}x{h} px, straight alpha
Frame rate  : {fps} fps (untimed steps); exact per-frame timing in frames.json

Three unique drawings — the three cells of one sheet, sliced in equal thirds and
de-keyed without trimming, so they share one canvas and one framing. The bank is
four steps: the half-open drawing plays again on the way back open, so frame
00003 is a copy of frame 00001.

Import into After Effects:
1. File > Import > File…
2. Select {who}_blink_00000.png and enable "PNG Sequence".
3. Interpret Footage > Main… — alpha: Straight (Unmatted).
4. Time-remap using the durations in frames.json for exact holds.
"""


def run(*cmd, **kw):
    env = dict(os.environ, PATH=NODE + os.pathsep + os.environ['PATH'])
    subprocess.run([str(c) for c in cmd], check=True, cwd=ROOT, env=env, **kw)


def rest_plate(tree, who):
    return os.path.join(tree, who, f'{who}_blink', f'{who}_blink_00000.png')


def build(who, tree, work):
    """Template = Sprite Studio's 3x1 mask sheet with cell 1 swapped for the real
    artwork, padded to exactly 21:9 so the route does not rescale the cells."""
    src = os.path.join(ROOT, rest_plate(tree, who))
    # The plate is the sequence's own first frame, so keep a copy: `split`
    # overwrites the folder it lives in.
    anchor = os.path.join(work, 'anchor.png')
    shutil.copyfile(src, anchor)
    gs = os.path.join(SCRIPTS, 'gridsheet.mjs')
    args = ['--cols', 3, '--rows', 1, '--cell', CELL, '--mode']
    run('node', gs, anchor, os.path.join(work, 'grid-mask.png'), *args, 'mask', '--bg', '00FF00')
    run('node', gs, anchor, os.path.join(work, 'grid-char.png'), *args, 'character', '--bg', '00FF00')

    mask = Image.open(os.path.join(work, 'grid-mask.png')).convert('RGB')
    char = Image.open(os.path.join(work, 'grid-char.png')).convert('RGB')
    cw = mask.width // 3
    tpl = mask.copy()
    tpl.paste(char.crop((0, 0, cw, mask.height)), (0, 0))
    h = round(mask.width / AR)
    pad = (h - mask.height) // 2
    out = Image.new('RGB', (mask.width, h), (0, 255, 0))
    out.paste(tpl, (0, pad))
    out.save(os.path.join(work, 'template.png'))
    json.dump({'cell': [cw, mask.height], 'pad_frac': pad / h},
              open(os.path.join(work, 'geom.json'), 'w'), indent=2)
    print(f'  template {out.size} ar {out.width/out.height:.4f}, vpad {pad}px, cell {cw}x{mask.height}')


def generate(who, tree, work):
    prompt = os.path.join(work, 'prompt.txt')
    with open(prompt, 'w') as fh:
        subprocess.run(['node', os.path.join(SCRIPTS, 'studioprompt.mjs'),
                        '--chart', 'blink', '--shapes', '3', '--cols', '3', '--rows', '1',
                        '--key', '00FF00', '--res', '4K'], check=True, stdout=fh, cwd=ROOT,
                       env=dict(os.environ, PATH=NODE + os.pathsep + os.environ['PATH']))
        fh.write(ANCHOR)
    run('python3', os.path.join(SCRIPTS, 'artgen.py'), 'sheet-wide', open(prompt).read(),
        '-i', os.path.join(work, 'anchor.png'), '-i', os.path.join(work, 'template.png'),
        '-o', os.path.join(work, 'raw-sheet.png'))


def align_left(keyed):
    """Put every frame's leftmost opaque pixel at the same x as the first.

    The drawings themselves are consistent — the model holds the character,
    the scale and the style across cells. What it does not hold is WHERE in the
    cell it starts: measured, the content began 22px further right in the
    half-open cell and 41px further right in the closed one, while the content's
    own width moved by 0.4%. That is a slide, not a redraw, and on playback it
    reads as the head drifting right as the eyes close.

    Only x is corrected. All three cells run off the bottom of the canvas, so
    the bust is already anchored vertically; the 4-5px difference in the top
    bound is the hair silhouette, and shifting to match it would introduce the
    vertical slide this removes horizontally.
    """
    boxes = {s: Image.open(p).getbbox() for s, p in keyed.items()}
    ref = boxes[CELLS[0]][0]
    for state, path in keyed.items():
        dx = ref - boxes[state][0]
        if dx == 0:
            continue
        im = Image.open(path).convert('RGBA')
        shifted = Image.new('RGBA', im.size, (0, 0, 0, 0))
        shifted.paste(im, (dx, 0))
        shifted.save(path)
        print(f'  {state}: shifted {dx:+d}px to align its left edge')


def split(who, tree, work):
    """Slice the sheet in equal thirds, de-key, write the sequence. That is all."""
    geom = json.load(open(os.path.join(work, 'geom.json')))
    sheet = Image.open(os.path.join(work, 'raw-sheet.png')).convert('RGB')
    # Undo the 21:9 padding proportionally — the route returns its own size
    # (4K/21:9 came back 6336x2688), so the pad is taken as a fraction.
    pad = round(geom['pad_frac'] * sheet.height)
    sheet = sheet.crop((0, pad, sheet.width, sheet.height - pad))
    cw = sheet.width // 3

    keyed = {}
    for i, state in enumerate(CELLS):
        cell = os.path.join(work, f'cell-{state}.png')
        sheet.crop((i * cw, 0, (i + 1) * cw, sheet.height)).save(cell)
        keyed[state] = os.path.join(work, f'cell-{state}-keyed.png')
        # No --trim: the three cells must stay co-registered on one canvas.
        run('python3', os.path.join(SCRIPTS, 'dekey.py'), cell, keyed[state], '--key', '00FF00')
    align_left(keyed)

    dst = os.path.join(ROOT, tree, who, f'{who}_blink')
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    os.makedirs(dst)
    frames = []
    for i, (state, ms) in enumerate(STEPS):
        name = f'{who}_blink_{i:05d}.png'
        shutil.copyfile(keyed[state], os.path.join(dst, name))
        frames.append({'index': i, 'file': name, 'durationMs': ms, 'blend': False})

    probe = Image.open(os.path.join(dst, frames[0]['file']))
    json.dump({'character': who, 'sequence': 'blink', 'fps': 7,
               'width': probe.width, 'height': probe.height,
               'frameCount': len(frames), 'frames': frames},
              open(os.path.join(dst, 'frames.json'), 'w'), indent=2)
    open(os.path.join(dst, 'README.txt'), 'w').write(README.format(
        who=who, n=len(frames), w=probe.width, h=probe.height, fps=7))
    print(f'  {dst}: {len(frames)} frames, {probe.width}x{probe.height}, '
          f'{sum(f["durationMs"] for f in frames)} ms')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('who')
    ap.add_argument('--stage', default='all', choices=('build', 'generate', 'split', 'all'))
    ap.add_argument('--tree', default='assets/sprites/characters-merge')
    ap.add_argument('--work', default=None)
    args = ap.parse_args()
    work = args.work or os.path.join(ROOT, 'assets/raw/characters', args.who, 'reskin/blinksheet')
    os.makedirs(work, exist_ok=True)
    for stage, fn in (('build', build), ('generate', generate), ('split', split)):
        if args.stage in (stage, 'all'):
            print(f'=== {args.who} · {stage} ===')
            fn(args.who, args.tree, work)


if __name__ == '__main__':
    main()
