#!/usr/bin/env python3
"""Export a step list as a Sprite Studio character-bank sequence.

  seqexport.py steps.json frames/ out_dir/ --manifest visemes.json \\
               --character eleanor --sequence hey-hey [--fps 12]

Writes the exact shape Laurah's clips already use in
`assets/sprites/guide-characters/laurah-dragonMaster/laurah_talk_*`:

    <character>_<sequence>_00000.png …   one PNG per animation step
    frames.json                          per-frame durations, the real timing
    README.txt                           the After Effects import note

One PNG per *step*, not per pose: a step that holds for 2.6 s is one file, and a
crossfade in-between is its own file with `"blend": true`. `fps` is metadata for
After Effects' interpret-footage rate — the authoritative timing is the
`durationMs` on each frame, which is why the README says to time-remap.
"""
import argparse
import json
import os
import shutil

from PIL import Image


def load_manifest(path: str) -> dict:
    data = json.load(open(path, encoding='utf-8'))
    if 'visemes' in data:
        return {v['id']: v['file'] for v in data['visemes']}
    if 'steps' in data:
        return {s['frameId']: s['file'] for s in data['steps'] if 'file' in s}
    raise SystemExit(f'{path}: no `visemes` or `steps` with files to map from')


README = """{base} — After Effects PNG sequence (character-bank sequence)
Generated by Sprite Studio

Character   : {character}
Sequence    : {sequence}
Files       : {count} PNGs — one per animation frame, {w}x{h} px, straight alpha
Frame rate  : {fps} fps (untimed steps); exact per-frame timing in frames.json

Import into After Effects:
1. File > Import > File…
2. Select {base}_00000.png and enable "PNG Sequence".
3. Interpret Footage > Main… — alpha: Straight (Unmatted).
4. Time-remap using the durations in frames.json for exact holds.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('steps')
    ap.add_argument('frames_dir')
    ap.add_argument('out_dir')
    ap.add_argument('--manifest', required=True)
    ap.add_argument('--character', required=True)
    ap.add_argument('--sequence', required=True)
    ap.add_argument('--fps', type=int, default=12)
    # Half the authored cell height by default. At full size the four clips
    # came to 254 MB of PNG; the authored plates stay in the pose folders,
    # so nothing is lost by delivering the sequence at delivery size.
    ap.add_argument('--height', type=int, default=None)
    args = ap.parse_args()

    steps = json.load(open(args.steps, encoding='utf-8'))['steps']
    files = load_manifest(args.manifest)

    loaded = {}
    for fid in {s['frameId'] for s in steps} | {s['blendWith'] for s in steps if s.get('blendWith')}:
        name = files.get(fid)
        if not name:
            raise SystemExit(f'step references frame {fid!r}, absent from the manifest')
        loaded[fid] = Image.open(os.path.join(args.frames_dir, name)).convert('RGBA')

    # Cells can differ by a pixel from grid rounding; one canvas for the clip.
    w = max(i.width for i in loaded.values())
    h = max(i.height for i in loaded.values())
    out_h = args.height or h // 2
    out_w = max(1, round(w * out_h / h))
    canvas = {}
    for fid, img in loaded.items():
        c = Image.new('RGBA', (w, h), (0, 0, 0, 0))
        c.paste(img, (0, 0))
        canvas[fid] = c if (out_w, out_h) == (w, h) else c.resize((out_w, out_h), Image.LANCZOS)
    w, h = out_w, out_h

    base = f'{args.character}_{args.sequence}'
    if os.path.isdir(args.out_dir):
        shutil.rmtree(args.out_dir)
    os.makedirs(args.out_dir)

    entries = []
    for i, s in enumerate(steps):
        img = canvas[s['frameId']]
        blend = bool(s.get('blendWith'))
        if blend:
            img = Image.blend(canvas[s['blendWith']], img, 0.5)
        name = f'{base}_{i:05d}.png'
        img.save(os.path.join(args.out_dir, name))
        entries.append({'index': i, 'file': name,
                        'durationMs': int(round(s['durationMs'])), 'blend': blend})

    json.dump({'character': args.character, 'sequence': args.sequence, 'fps': args.fps,
               'width': w, 'height': h, 'frameCount': len(entries), 'frames': entries},
              open(os.path.join(args.out_dir, 'frames.json'), 'w'), indent=2)
    open(os.path.join(args.out_dir, 'README.txt'), 'w').write(
        README.format(base=base, character=args.character, sequence=args.sequence,
                      count=len(entries), w=w, h=h, fps=args.fps))

    total = sum(e['durationMs'] for e in entries)
    size = sum(os.path.getsize(os.path.join(args.out_dir, f))
               for f in os.listdir(args.out_dir)) / 1048576
    print(f'  {args.out_dir}: {len(entries)} frames, {w}x{h}, {total} ms, {size:.0f} MB')


if __name__ == '__main__':
    main()
