import Phaser from 'phaser';
import themeJson from '../data/ui-theme.json';

/**
 * UI theme runtime — the game side of the UI Builder satellite tool.
 *
 * `src/data/ui-theme.json` is GENERATED by tools/uibuilder (never hand-edit):
 * per-element overrides (position offsets, scale, alpha, per-part text styles,
 * tints, texture swaps) plus color parameters for the TextureFactory ui_*
 * chrome textures. An EMPTY theme means the game renders exactly its authored
 * look — every override is a delta on top of the values components set in code,
 * so gameplay logic (tweens, visibility toggles, layout) keeps working.
 *
 * UI components register their root container + named parts with `uiRegistry`;
 * the theme is applied at registration (and re-applied live in uiedit mode via
 * the bridge in uiEdit.ts).
 */

export {
  mergeElementPatch,
  prunePatch,
  sanitizeThemeDoc,
  type CustomComponent,
  type CustomLayer,
  type UiElementPatch,
  type UiPartPatch,
  type UiTextPatch,
  type UiThemeDoc
} from './themeCore';
import {
  hexToNum,
  mergeElementPatch,
  prunePatch,
  sanitizeThemeDoc,
  type UiElementPatch,
  type UiPartPatch,
  type UiTextPatch,
  type UiThemeDoc
} from './themeCore';

/* ------------------------------- registry ------------------------------- */

type UiNode = Phaser.GameObjects.Container | Phaser.GameObjects.Image | Phaser.GameObjects.Text;
/** Structural shape shared by images/texts/containers/shapes — parts only need
 *  the transform/alpha/visible surface, whatever concrete class they are. */
type PartObj = Phaser.GameObjects.GameObject & {
  x?: number;
  y?: number;
  scaleX?: number;
  scaleY?: number;
  setPosition?: (x: number, y: number) => unknown;
  setScale?: (x: number, y?: number) => unknown;
  setAlpha?: (a: number) => unknown;
  setVisible?: (v: boolean) => unknown;
};

export type UiPartKind = 'text' | 'image' | 'shape';

/** A numeric layout knob a component exposes to the UI Builder (e.g. bubble width). */
export interface UiParamSpec {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
  dflt: number;
}

export interface UiRegisterOpts {
  /** Element re-positions itself (tooltip) — it consumes offsetOf() itself. */
  selfPositioned?: boolean;
  /** Parts whose transform the component's own layout() owns — the registry
   *  applies STYLE only; the layout consumes partOffsetOf() for dx/dy/scale. */
  selfLaidOutParts?: string[];
  /** Re-run the component's layout after a theme change (consumes params/offsets). */
  relayout?: () => void;
  /** Called when the editor peeks a hidden element (show sample content etc). */
  onPeek?: (on: boolean) => void;
  /** Layout knobs shown in the tool's Component section. */
  paramsSpec?: UiParamSpec[];
}

interface PartBase {
  x: number;
  y: number;
  scaleX: number;
  scaleY: number;
  alpha: number;
  textureKey?: string;
  text?: Required<UiTextPatch>;
}

interface RegisteredPart {
  name: string;
  kind: UiPartKind;
  obj: PartObj;
  base: PartBase;
}

interface RegisteredElement {
  id: string;
  label: string;
  group: string;
  node: UiNode;
  scene: Phaser.Scene;
  base: { x: number; y: number; scaleX: number; scaleY: number; depth: number; alpha: number };
  parts: RegisteredPart[];
  opts: UiRegisterOpts;
}

/** Public descriptor shape shared with the UI Builder tool over postMessage. */
export interface UiElementInfo {
  id: string;
  label: string;
  group: string;
  base: { x: number; y: number; scaleX: number; scaleY: number; depth: number };
  bounds: { x: number; y: number; w: number; h: number };
  patch: UiElementPatch;
  parts: Array<{ name: string; kind: UiPartKind; base: PartBase; textureKey?: string; bounds?: { x: number; y: number; w: number; h: number } }>;
  paramsSpec: UiParamSpec[];
}

export class UiRegistry {
  readonly elements = new Map<string, RegisteredElement>();
  doc: UiThemeDoc = sanitizeThemeDoc(themeJson);
  /** uiedit-mode hook: the bridge subscribes to re-outline after changes. */
  onChanged: ((id: string) => void) | null = null;
  /** Set by the PartAnimator (via CustomUiManager): applyPart reports every
   *  image part's `sequence` patch so animated parts attach/detach with the
   *  theme — the registry itself stays playback-free. */
  partSequenceHook:
    | ((elementId: string, partName: string, img: Phaser.GameObjects.Image, sequence: string | null, loop: boolean | undefined) => void)
    | null = null;

  register(
    scene: Phaser.Scene,
    id: string,
    label: string,
    group: string,
    node: UiNode,
    parts: Record<string, PartObj> = {},
    opts: UiRegisterOpts = {}
  ): void {
    const el: RegisteredElement = {
      id,
      label,
      group,
      node,
      scene,
      opts,
      base: { x: node.x, y: node.y, scaleX: node.scaleX, scaleY: node.scaleY, depth: node.depth, alpha: node.alpha },
      parts: Object.entries(parts).map(([name, obj]) => ({
        name,
        kind: obj instanceof Phaser.GameObjects.Text ? 'text' : obj instanceof Phaser.GameObjects.Image ? 'image' : 'shape',
        obj,
        base: this.captureBase(obj)
      }))
    };
    this.elements.set(id, el);
    this.applyElement(id);
  }

  private captureBase(obj: PartObj): PartBase {
    const base: PartBase = {
      x: obj.x ?? 0,
      y: obj.y ?? 0,
      scaleX: obj.scaleX ?? 1,
      scaleY: obj.scaleY ?? 1,
      alpha: (obj as { alpha?: number }).alpha ?? 1
    };
    if (obj instanceof Phaser.GameObjects.Image) base.textureKey = obj.texture.key;
    if (obj instanceof Phaser.GameObjects.Text) {
      const s = obj.style;
      base.text = {
        color: String(s.color ?? '#ffffff'),
        fontSize: Math.round(parseFloat(String(s.fontSize ?? '32'))),
        fontStyle: String(s.fontStyle ?? ''),
        fontFamily: String(s.fontFamily ?? 'sans-serif'),
        stroke: String(s.stroke ?? '#000000'),
        strokeThickness: s.strokeThickness ?? 0
      };
    }
    return base;
  }

  /** The persisted offset for elements that re-position themselves (tooltip). */
  offsetOf(id: string): { dx: number; dy: number } {
    const p = this.doc.elements[id];
    return { dx: p?.dx ?? 0, dy: p?.dy ?? 0 };
  }

  /** Offset/scale for a part whose transform the component's layout owns. */
  partOffsetOf(id: string, part: string): { dx: number; dy: number; scale: number } {
    const p = this.doc.elements[id]?.parts?.[part];
    return { dx: p?.dx ?? 0, dy: p?.dy ?? 0, scale: p?.scale ?? 1 };
  }

  /** A component layout knob (falls back to the paramsSpec default). */
  paramOf(id: string, key: string, dflt: number): number {
    return this.doc.elements[id]?.params?.[key] ?? dflt;
  }

  /** Merge a patch into the doc and re-apply it to the live element. */
  setPatch(id: string, patch: UiElementPatch): void {
    this.doc.elements[id] = mergeElementPatch(this.doc.elements[id], patch);
    this.applyElement(id);
    this.onChanged?.(id);
  }

  resetElement(id: string): void {
    delete this.doc.elements[id];
    this.applyElement(id);
    this.onChanged?.(id);
  }

  applyElement(id: string): void {
    const el = this.elements.get(id);
    if (!el || !el.node.scene) return;
    const p = this.doc.elements[id] ?? {};
    if (!el.opts.selfPositioned) el.node.setPosition(el.base.x + (p.dx ?? 0), el.base.y + (p.dy ?? 0));
    const s = p.scale ?? 1;
    el.node.setScale(el.base.scaleX * s, el.base.scaleY * s);
    el.node.setAlpha(p.alpha ?? el.base.alpha);
    if (p.visible !== undefined) el.node.setVisible(p.visible);
    // Depth only when overridden — scenes assign authored depths AFTER
    // registration, so restoring a stale base here would undo them.
    if (p.depth !== undefined && p.depth !== null) el.node.setDepth(p.depth);
    // A part that IS the root (text-only elements) gets style/tint only — the
    // element-level transform already owns position/scale/alpha. Parts owned by
    // the component's own layout() are also style-only here (the layout consumes
    // partOffsetOf), so live game re-layouts never fight the theme.
    const selfLaid = new Set(el.opts.selfLaidOutParts ?? []);
    for (const part of el.parts) {
      this.applyPart(el.id, part, p.parts?.[part.name], part.obj === (el.node as PartObj) || selfLaid.has(part.name));
    }
    el.opts.relayout?.();
  }

  private applyPart(elementId: string, part: RegisteredPart, patch: UiPartPatch | undefined, styleOnly = false): void {
    const p = patch ?? {};
    const obj = part.obj;
    if (!styleOnly) {
      obj.setPosition?.(part.base.x + (p.dx ?? 0), part.base.y + (p.dy ?? 0));
      const s = p.scale ?? 1;
      obj.setScale?.(part.base.scaleX * s, part.base.scaleY * s);
      obj.setAlpha?.(p.alpha ?? part.base.alpha);
      if (p.visible !== undefined) obj.setVisible?.(p.visible);
    }
    if (obj instanceof Phaser.GameObjects.Image) {
      if (p.tint) obj.setTint(hexToNum(p.tint));
      else obj.clearTint();
      const seq = p.sequence ?? null;
      if (!seq) {
        // Static texture only when NO sequence plays here — the animator owns
        // the texture (and contain-fit scale) while a sequence is attached.
        const wanted = p.texture ?? part.base.textureKey;
        if (wanted && obj.texture.key !== wanted && obj.scene.textures.exists(wanted)) obj.setTexture(wanted);
      }
      this.partSequenceHook?.(elementId, part.name, obj, seq, p.loop);
    }
    if (obj instanceof Phaser.GameObjects.Text && part.base.text) {
      const b = part.base.text;
      const t = p.text ?? {};
      obj.setStyle({
        color: t.color ?? b.color,
        fontSize: `${t.fontSize ?? b.fontSize}px`,
        fontStyle: t.fontStyle ?? b.fontStyle,
        fontFamily: t.fontFamily ?? b.fontFamily,
        stroke: t.stroke ?? b.stroke,
        strokeThickness: t.strokeThickness ?? b.strokeThickness
      });
    }
  }

  /** Everything the UI Builder needs to render its panels. */
  describe(id: string): UiElementInfo | null {
    const el = this.elements.get(id);
    if (!el || !el.node.scene) return null;
    const b = el.node.getBounds();
    return {
      id: el.id,
      label: el.label,
      group: el.group,
      base: el.base,
      bounds: { x: b.x, y: b.y, w: b.width, h: b.height },
      patch: this.doc.elements[id] ?? {},
      paramsSpec: el.opts.paramsSpec ?? [],
      parts: el.parts.map((p) => {
        const pb = (p.obj as { getBounds?: () => Phaser.Geom.Rectangle }).getBounds?.();
        return {
          name: p.name,
          kind: p.kind,
          base: p.base,
          textureKey: p.base.textureKey,
          bounds: pb ? { x: pb.x, y: pb.y, w: pb.width, h: pb.height } : undefined
        };
      })
    };
  }

  describeAll(): UiElementInfo[] {
    return [...this.elements.keys()]
      .map((id) => this.describe(id))
      .filter((d): d is UiElementInfo => d !== null);
  }

  /** Doc with empty/default patches pruned — what gets saved to ui-theme.json. */
  exportDoc(): UiThemeDoc {
    const elements: Record<string, UiElementPatch> = {};
    for (const [id, patch] of Object.entries(this.doc.elements)) {
      const pruned = prunePatch(patch);
      if (pruned) elements[id] = pruned;
    }
    return {
      version: 1,
      textures: this.doc.textures,
      elements,
      custom: this.doc.custom,
      assets: this.doc.assets,
      sequences: this.doc.sequences,
      replacements: this.doc.replacements
    };
  }

  /** Anchor override for a replaced texture key (hand fingertip, arrow tip). */
  replacementAnchor(key: string): [number, number] | null {
    const rep = this.doc.replacements[key];
    return rep && rep.anchorX !== undefined && rep.anchorY !== undefined ? [rep.anchorX, rep.anchorY] : null;
  }
}

/** Singleton — UI components register here; the uiedit bridge drives it. */
export const uiRegistry = new UiRegistry();

/** Texture key an upload is stored under. */
export const uploadKey = (name: string): string => `up_${name}`;

export { sequenceFrameKey } from './themeCore';
import { sequenceFrameKey } from './themeCore';

/** Ensure every frame of a sequence is a live texture (idempotent). Frames load
 *  async from their data URLs; returns the ordered frame keys immediately so a
 *  caller can wire playback and let textures pop in as they decode. */
export function ensureSequenceTextures(scene: Phaser.Scene, name: string, frames: string[]): string[] {
  return frames.map((uri, i) => {
    const key = sequenceFrameKey(name, i);
    if (!scene.textures.exists(key)) scene.textures.addBase64(key, uri);
    return key;
  });
}

/**
 * Repaint a GENERATED (canvas) texture with other art IN PLACE — the key and
 * the CanvasTexture object survive, so every consumer (tutorial hand, arrows,
 * icons, buttons) updates instantly and no interaction can break: events live
 * on game objects, and none of them are touched. Contain-fit preserves the
 * upload's aspect ratio inside the original canvas.
 */
export function repaintTextureWith(scene: Phaser.Scene, key: string, srcKey: string): boolean {
  const tm = scene.textures;
  if (!tm.exists(key) || !tm.exists(srcKey)) return false;
  const tex = tm.get(key);
  if (!(tex instanceof Phaser.Textures.CanvasTexture)) return false;
  const src = tm.get(srcKey).getSourceImage() as HTMLImageElement | HTMLCanvasElement;
  if (!src.width || !src.height) return false;
  const g = tex.getContext();
  g.save();
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.clearRect(0, 0, tex.width, tex.height);
  const fit = Math.min(tex.width / src.width, tex.height / src.height);
  const w = src.width * fit;
  const h = src.height * fit;
  g.drawImage(src as CanvasImageSource, (tex.width - w) / 2, (tex.height - h) / 2, w, h);
  g.restore();
  tex.refresh();
  return true;
}

/** Apply every saved texture replacement (called once after preload, before
 *  any scene builds objects — and re-applied live by the editor bridge). */
export function applyUiReplacements(scene: Phaser.Scene): void {
  for (const [key, rep] of Object.entries(uiRegistry.doc.replacements)) {
    repaintTextureWith(scene, key, uploadKey(rep.src));
  }
}
