#!/usr/bin/env python3
"""Author a NEW map mask — grid first, island silhouette derived from it.

This is the inverse of trace.py/grid.py: nothing is read from the backdrop.
Tiles are authored in lattice space, then the island bodies are generated by
the border law documented in README.md — the silhouette is the deck extruded
by the rock skirt, rounded off.

Four rules drive the layout:
  1. every tile row and column is at least 3 cells long — a "row" being a
     lattice line, the two diagonal families you actually read on screen.
     Every island is authored from >= 3x3 rectangles and diagonal bands, so a
     run through any cell is at least as long as the shape it came from; the
     result is re-checked cell by cell before anything is drawn.
  2. every south-facing rim carries rock below it, and it is DOWNWARDS that
     the left side gains its room, not sideways. The skirt is a straight-down
     curtain, deep under a south-west facing rim and shallower — never absent —
     under a south-east one; see INBOARD below for how the two are told apart.
     Neither hangs to a constant depth: a two-octave profile cuts rock lobes
     into both, floored at DEPTH_MIN so no stretch of rim comes out flat.
     Measured on the landmass: 95 px of drop under the left rim against 39
     under the right (median 76, reaching 250 under the deepest lobe), while
     the sideways margins stay small on both (65 / 37).
  3. the reference archipelago pattern is kept — a central landmass, the
     gatehouse slab running into the lava terrace on the east, a small pad off
     to the south — but at three cells minimum a pad is far bigger than its
     traced counterpart, so the backdrop's two micro-pads (a 3-tile rune pad
     and a 1-tile lantern isle) collapse into the single southern pad.
  4. the main landmass is bigger than the traced one: 150 tiles against 47,
     at 1.06x its silhouette area.

The lattice is deliberately finer than the backdrop's (138x80 against 207x120,
same 1.725 aspect), which is what makes the map bigger: 238 playable tiles
against the 76 traced off the art, in the same frame.

Outputs into tools/mapmask/out/:
  design-mask.png      island silhouettes, white on black
  design-grid.png      the tile grid, blue on black
  design-map-mask.png  the two combined (the deliverable)
  design-layout.json   lattice, origins and the cell list per island

Usage: python3 tools/mapmask/design.py
"""
import argparse
import json
import os

import cv2
import numpy as np
from scipy.ndimage import gaussian_filter

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'tools', 'mapmask', 'out')

CANVAS = (1632, 2610)        # h, w — matches the backdrop
# Two thirds of the 207x120 lattice measured off the backdrop, same 1.725
# aspect. Smaller tiles mean 2.25x the playable cells in the same frame.
TILE_W, TILE_H = 138, 80

# The skirt hangs STRAIGHT DOWN — rock does. What differs between the two
# lower rims is how far it hangs, not which way it leans:
#
#   DROP_SW  the deep curtain under a south-west facing rim, where you are
#            looking at the underside of the island
#   DROP_SE  the shallower one under a south-east facing rim, kept modest
#            because the grid hugs the mask on that side — but never zero,
#            or the right rim reads as a flat cut instead of rock
#
# Splitting them needs a way to say "inboard of the SE rim". INBOARD sweeps
# the deck along the SE tile edge (-TILE_W, +TILE_H): translating a shape
# along one of its own edges leaves that edge on the same line, so the swept
# region covers everything down-LEFT of the south-west rim and stops dead at
# the south-east one. Intersecting the deep curtain with it puts the bottom
# relief on the left and leaves the right rim alone.
INBOARD = (-2 * TILE_W, 2 * TILE_H)
DROP_SW = round(1.35 * TILE_H)
DROP_SE = round(0.65 * TILE_H)
LIP = round(0.10 * TILE_H)   # uniform lip: no tile ever sits flush to the rim

# Neither curtain hangs to a constant depth — real rock does not. Each is cut
# by a two-octave profile along x: broad lobes about a tile and a half wide,
# plus a chunkier ripple. DEPTH_MIN is the floor, so no stretch of rim is ever
# left flat.
DEPTH_MIN = 0.60
LOBE_SIGMA = 1.5 * TILE_W
CHUNK_SIGMA = 0.35 * TILE_W

NOISE_AMP = round(0.17 * TILE_H)     # organic boundary displacement, px
NOISE_SIGMA = round(0.30 * TILE_H)   # its correlation length
CLOSE_R = round(0.33 * TILE_H)       # the scalloped rounding of the reference art
OPEN_R = round(0.15 * TILE_H)

GRID_COLOR = (255, 140, 0)   # BGR — blue
STROKE = 3

# Islands in lattice space. `rects` are (n0, n1, m0, m1) inclusive and must be
# at least 3x3; `band` is (n0, n1, m0, m1, k) — the diagonal core, every cell
# with |n - m| <= k, which is what makes a landmass read as a chunky rhombus
# instead of a long ribbon. Both forms are run-checked before anything is
# drawn. `center` is where the island's tile bbox lands on the canvas.
#
# The reference backdrop resolves to four island bodies, not six: the brazier
# pad is part of the main landmass and the gatehouse slab is the head of the
# eastern ribbon. That grouping is kept here — at three cells minimum a
# free-floating pad is nine times its traced size and the sea closes up.
ISLANDS = [
    {
        'id': 'main',
        'label': 'Central keep — rhombic core with the brazier shoulder north '
                 'and a south-east lobe',
        'center': (800, 780),
        # rhombic core, then a lobe stepping south-east
        'band': (0, 11, 0, 11, 6),
        'rects': [(12, 17, 9, 14)],
    },
    {
        'id': 'east',
        'label': 'Gatehouse slab into the lava-fall terrace, stepping south-east',
        'center': (2075, 520),
        'rects': [(0, 4, 0, 4), (3, 7, 2, 6), (6, 10, 4, 8)],
    },
    {
        'id': 'runepad',
        'label': 'Rune pad / lantern isle (south-east)',
        'center': (1880, 1300),
        'rects': [(0, 4, 0, 4)],
    },
]

# A hub world: one dominant landmass carrying nearly all the play surface, and
# a single small satellite. `minRun` relaxes the 3-cell rule per island — the
# satellite is deliberately 2x2, which the archipelago layout would reject.
HUB_ISLANDS = [
    {
        'id': 'hub',
        'label': 'The hub — a broad irregular plateau: wobbled coastline with '
                 'bays and headlands, deliberately NOT a diamond',
        'center': (1030, 760),
        # (ru, rv, wobble, seed) in screen-lattice space, then sliver-pruned
        'blob': (13, 12, 0.18, 18),
    },
    {
        'id': 'outpost',
        'label': 'Outpost — a 2x2 pad off the hub\'s eastern rim',
        'center': (2300, 1010),
        'rects': [(0, 1, 0, 1)],
        'minRun': 2,
    },
]

LAYOUTS = {'archipelago': (ISLANDS, 'design'), 'hub': (HUB_ISLANDS, 'hub')}


def disk(r):
    return cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2 * r + 1, 2 * r + 1))


def cells_of(isl):
    out = set()
    floor = isl.get('minRun', 3)
    for n0, n1, m0, m1 in isl.get('rects', []):
        if n1 - n0 < floor - 1 or m1 - m0 < floor - 1:
            raise SystemExit(f'rect {(n0, n1, m0, m1)} is thinner than {floor} cells')
        for n in range(n0, n1 + 1):
            for m in range(m0, m1 + 1):
                out.add((n, m))
    if 'blob' in isl:
        # An irregular landmass: an ellipse in SCREEN-lattice space (u = n - m
        # runs across, v = n + m runs down) whose radius wobbles with three
        # harmonics. That gives bays and headlands instead of a perfect
        # diamond, and it is deterministic — same seed, same coastline.
        import math
        ru, rv, wob, seed = isl['blob']
        rng = np.random.default_rng(seed)
        ph = rng.uniform(0, 2 * math.pi, 3)
        span = int(max(ru, rv)) + 3
        for n in range(-span, span + 1):
            for m in range(-span, span + 1):
                u, v = n - m, n + m
                d = math.hypot(u / ru, v / rv)
                if d == 0:
                    out.add((n, m))
                    continue
                th = math.atan2(v / rv, u / ru)
                r = 1 + wob * (0.6 * math.sin(3 * th + ph[0])
                               + 0.3 * math.sin(5 * th + ph[1])
                               + 0.2 * math.sin(7 * th + ph[2]))
                if d <= r:
                    out.add((n, m))
    if 'band' in isl:
        n0, n1, m0, m1, k = isl['band']
        for n in range(n0, n1 + 1):
            for m in range(m0, m1 + 1):
                if abs(n - m) <= k:
                    out.add((n, m))
    out -= {tuple(c) for c in isl.get('omit', [])}
    # A wobbling coastline throws off 1-2 cell spurs that break the run rule.
    # Shave them iteratively: drop any cell sitting in a run shorter than the
    # floor, and repeat until stable. The outline stays irregular; it just
    # stops growing slivers no tile row could use.
    if 'blob' in isl:
        while True:
            drop = set()
            for axis in (0, 1):
                lines = {}
                for n, m in out:
                    key, val = (n, m) if axis == 0 else (m, n)
                    lines.setdefault(key, []).append(val)
                for key, vals in lines.items():
                    vals = sorted(vals)
                    run = [vals[0]]
                    for a, b in zip(vals, vals[1:]):
                        if b == a + 1:
                            run.append(b)
                        else:
                            if len(run) < floor:
                                drop |= {(key, v) if axis == 0 else (v, key) for v in run}
                            run = [b]
                    if len(run) < floor:
                        drop |= {(key, v) if axis == 0 else (v, key) for v in run}
            if not drop:
                break
            out -= drop
    return out


def runs(cells, axis):
    """Lengths of every contiguous run along one lattice axis."""
    lines = {}
    for n, m in cells:
        key, val = (n, m) if axis == 0 else (m, n)
        lines.setdefault(key, []).append(val)
    lengths = []
    for vals in lines.values():
        vals = sorted(vals)
        run = 1
        for a, b in zip(vals, vals[1:]):
            if b == a + 1:
                run += 1
            else:
                lengths.append(run)
                run = 1
        lengths.append(run)
    return lengths


def diamond(n, m):
    """Tile polygon in un-translated screen space."""
    cx = (n - m) * TILE_W / 2.0
    cy = (n + m) * TILE_H / 2.0
    return np.array([[cx, cy - TILE_H / 2], [cx + TILE_W / 2, cy],
                     [cx, cy + TILE_H / 2], [cx - TILE_W / 2, cy]])


def place(cells, center):
    """Translate the island so its tile bbox is centred on `center`."""
    polys = {k: diamond(*k) for k in cells}
    allp = np.concatenate(list(polys.values()))
    lo, hi = allp.min(0), allp.max(0)
    off = np.array(center) - (lo + hi) / 2.0
    return {k: p + off for k, p in polys.items()}, (lo + off, hi + off)


def shift(mask, dx, dy):
    out = np.zeros_like(mask)
    h, w = mask.shape
    sx0, sx1 = max(0, -dx), min(w, w - dx)
    sy0, sy1 = max(0, -dy), min(h, h - dy)
    if sx1 <= sx0 or sy1 <= sy0:
        return out
    out[sy0 + dy:sy1 + dy, sx0 + dx:sx1 + dx] = mask[sy0:sy1, sx0:sx1]
    return out


def sweep(mask, vec):
    """Union of the mask translated along a vector — the extrusion itself."""
    dx, dy = vec
    steps = max(abs(dx), abs(dy))
    out = mask.copy()
    for i in range(1, steps + 1):
        t = i / steps
        out = np.maximum(out, shift(mask, int(round(dx * t)), int(round(dy * t))))
    return out


def depth_profile(rng, width, peak):
    """Per-column skirt depth: broad rock lobes plus a chunkier ripple."""
    def octave(sigma):
        n = gaussian_filter(rng.standard_normal(width).astype(np.float32), sigma)
        return (n - n.min()) / (np.ptp(n) + 1e-6)
    n = 0.7 * octave(LOBE_SIGMA) + 0.3 * octave(CHUNK_SIGMA)
    n = (n - n.min()) / (np.ptp(n) + 1e-6)
    return peak * (DEPTH_MIN + (1 - DEPTH_MIN) * n)


def curtain(deck, depth):
    """Hang rock straight down from the deck, `depth[x]` deep in column x."""
    out = np.zeros_like(deck)
    for i in range(1, int(depth.max()) + 1):
        keep = depth >= i
        if not keep.any():
            break
        out = np.maximum(out, shift(deck, 0, i) * keep[None, :])
    return out


def silhouette(deck, rng):
    """The border law: deck, extruded by the skirt, rounded, roughened."""
    core = cv2.dilate(deck, disk(LIP))          # containment guarantee
    inboard = np.maximum(deck, sweep(deck, INBOARD))
    w = deck.shape[1]
    body = np.maximum(
        cv2.bitwise_and(curtain(deck, depth_profile(rng, w, DROP_SW)), inboard),
        curtain(deck, depth_profile(rng, w, DROP_SE)))
    body = cv2.dilate(np.maximum(body, deck), disk(LIP))

    # organic rim: displace the boundary by a low-frequency field
    inv = cv2.bitwise_not(body)
    sdf = (cv2.distanceTransform(inv, cv2.DIST_L2, 5)
           - cv2.distanceTransform(body, cv2.DIST_L2, 5))
    field = gaussian_filter(rng.standard_normal(body.shape).astype(np.float32),
                            NOISE_SIGMA)
    field *= NOISE_AMP / (field.std() + 1e-6)
    body = ((sdf < field).astype(np.uint8) * 255)
    body = np.maximum(body, core)

    body = cv2.morphologyEx(body, cv2.MORPH_CLOSE, disk(CLOSE_R))
    body = cv2.morphologyEx(body, cv2.MORPH_OPEN, disk(OPEN_R))
    body = np.maximum(body, core)
    holes = np.zeros((body.shape[0] + 2, body.shape[1] + 2), np.uint8)
    flood = body.copy()
    cv2.floodFill(flood, holes, (0, 0), 255)
    return np.maximum(body, cv2.bitwise_not(flood))


def margins(body, deck):
    """How far the rim sits outside the grid: sideways, then downwards.

    The last two are the point of the whole exercise — the rock has to read as
    hanging BELOW the south-west rim, not spreading out to the left of it, so
    the left drop should dominate everything else here.
    """
    left, right = [], []
    for y in range(body.shape[0]):
        d = np.nonzero(deck[y])[0]
        b = np.nonzero(body[y])[0]
        if len(d) and len(b):
            left.append(d[0] - b[0])
            right.append(b[-1] - d[-1])
    cols = np.nonzero(deck.any(0))[0]
    mid = (cols[0] + cols[-1]) / 2 if len(cols) else 0
    drop = {'l': [], 'r': []}
    for x in cols:
        d = np.nonzero(deck[:, x])[0]
        b = np.nonzero(body[:, x])[0]
        if len(d) and len(b):
            drop['l' if x < mid else 'r'].append(b[-1] - d[-1])
    med = lambda v: int(np.median(v)) if v else 0
    return med(left), med(right), med(drop['l']), med(drop['r'])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--layout', default='archipelago', choices=list(LAYOUTS))
    args = ap.parse_args()
    islands, prefix = LAYOUTS[args.layout]
    os.makedirs(OUT, exist_ok=True)
    rng = np.random.default_rng(7)
    h, w = CANVAS
    mask = np.zeros((h, w), np.uint8)
    grid = np.zeros((h, w, 3), np.uint8)
    bodies, layout, total = {}, [], 0

    for isl in islands:
        cells = cells_of(isl)
        floor = isl.get('minRun', 3)
        for axis, name in ((0, 'column'), (1, 'row')):
            short = min(runs(cells, axis))
            if short < floor:
                raise SystemExit(f'{isl["id"]}: a {name} is only {short} cells')
        polys, (lo, hi) = place(cells, isl['center'])

        deck = np.zeros((h, w), np.uint8)
        for p in polys.values():
            cv2.fillConvexPoly(deck, np.round(p).astype(np.int32), 255)
        body = silhouette(deck, rng)
        bodies[isl['id']] = body

        ml, mr, dl, dr = margins(body, deck)
        print(f'  {isl["id"]:8s} {len(cells):3d} cells  '
              f'bbox {int(hi[0] - lo[0]):4d}x{int(hi[1] - lo[1]):4d} at '
              f'({int(lo[0])},{int(lo[1])})  side L{ml:3d} R{mr:3d}  '
              f'drop L{dl:3d} R{dr:3d}')

        mask = np.maximum(mask, body)
        for p in polys.values():
            cv2.polylines(grid, [np.round(p).astype(np.int32)], True,
                          GRID_COLOR, STROKE, cv2.LINE_AA)
        total += len(cells)
        entry = {'id': isl['id'], 'label': isl['label'],
                 'center': isl['center'], 'cells': sorted(cells)}
        for key in ('rects', 'band', 'blob', 'omit', 'minRun'):
            if key in isl:
                entry[key] = isl[key]
        layout.append(entry)

    ids = list(bodies)
    for i, a in enumerate(ids):
        for b in ids[i + 1:]:
            if np.any(cv2.bitwise_and(bodies[a], bodies[b])):
                print(f'  ! {a} and {b} overlap')
            else:
                far = cv2.distanceTransform(cv2.bitwise_not(bodies[a]),
                                            cv2.DIST_L2, 5)
                gap = int(far[bodies[b] > 0].min())
                if gap < 40:
                    print(f'  ! {a}/{b} gap only {gap} px')

    combined = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
    combined[grid.any(-1) > 0] = grid[grid.any(-1) > 0]

    cv2.imwrite(os.path.join(OUT, f'{prefix}-mask.png'), mask)
    cv2.imwrite(os.path.join(OUT, f'{prefix}-grid.png'), grid)
    cv2.imwrite(os.path.join(OUT, f'{prefix}-map-mask.png'), combined)
    with open(os.path.join(OUT, f'{prefix}-layout.json'), 'w') as fh:
        json.dump({'imageSize': [w, h], 'lattice': {'tileW': TILE_W, 'tileH': TILE_H},
                   'skirt': {'inboard': INBOARD, 'dropSW': DROP_SW,
                             'dropSE': DROP_SE, 'lip': LIP},
                   'islands': layout}, fh, indent=2)
    print(f'{total} tiles, {len(islands)} islands -> {OUT}/{prefix}-map-mask.png')


if __name__ == '__main__':
    main()
