/**
 * CHARACTER ATLAS CLIPS — the frame-sheet animations authored in the Align
 * Studio (Sprite Studio /align) and pushed through /__animalign.
 *
 * `src/data/character-anims.json` is GENERATED by scripts/apply-anim-align.mjs:
 * each clip names a staged sheet under assets/sprites/anims/ plus the transform
 * that registers it onto the character's board anchor. The convention (shared
 * with the tool and the analyzer): a frame with {scale, dx, dy} draws at
 *
 *   x = anchorX + dx - frameWidth  * scale / 2
 *   y = anchorY + dy - frameHeight * scale
 *
 * i.e. scale is game px per atlas px and dx/dy move the frame's bottom-centre
 * off the anchor. `clipOrigin` folds that into a Phaser origin so a sprite
 * PLACED at the anchor renders exactly where the tool showed it.
 *
 * Phaser-free on purpose (like worldArt.ts): the rules here are unit-testable
 * in node, and the scenes only spend a couple of lines on the Phaser calls.
 */
import characterAnimsJson from '../data/character-anims.json';

export interface CharacterClip {
  /** path under assets/, e.g. 'sprites/anims/eleanor/idle.webp' */
  file: string;
  frames: number;
  frameWidth: number;
  frameHeight: number;
  fps: number;
  loop: boolean;
  /** game px per atlas px (already corrected for any staging downscale) */
  scale: number;
  dx: number;
  dy: number;
  /**
   * Where the clip plays. 'board' (default) = on the standee/board anchor.
   * 'portrait' = the dialogue bubble's ring ONLY — talking/blinking sets live
   * there (they replace the disc-atlas animation) and never on the board.
   */
  stage?: 'board' | 'portrait';
  /**
   * Named frame sub-ranges [start, endExclusive] — the fly clip's
   * takeoff/loop/landing phases. Absent = the clip plays whole. (Typed as
   * number[] because a JSON import cannot carry tuples; validation enforces
   * exactly two integers.)
   */
  segments?: Record<string, number[]>;
  /** the raw authoring frame size, kept so the tool can round-trip */
  srcFrameWidth?: number;
  srcFrameHeight?: number;
}

/**
 * How a character's PORTRAIT clips sit in the dialogue ring: the frame is drawn
 * top-anchored at ring-centre + dy, scaled so the whole frame is `height`
 * display px, and the head copy (drawn ABOVE the ring band) is the top
 * `headCrop` fraction of the frame — the split the guide's disc always had.
 */
export interface PortraitView {
  height: number;
  dy: number;
  headCrop: number;
}

export interface CharacterAnimEntry {
  clips: Record<string, CharacterClip>;
  /**
   * For BOARD DRAGONS: the `chain:tier` this character's clips dress (e.g.
   * 'ember_dragon:3' for the red whelp). World characters have none — they are
   * looked up by wardrobe key instead.
   */
  board?: string;
  /**
   * For BOARD DRAGONS bought in the Emporium: the worn skin id this character
   * answers to (e.g. 'frost' → the Frost dragon's own clip set dresses an
   * `ember_dragon:3` wearing the frost skin). Absent = the chain's bare look.
   */
  skin?: string;
  /** Ring framing for this character's portrait-stage clips. */
  portrait?: PortraitView;
}

export interface CharacterAnimsData {
  version: number;
  characters: Record<string, CharacterAnimEntry>;
}

export const CHARACTER_ANIMS: CharacterAnimsData = characterAnimsJson as CharacterAnimsData;

/** The staged clip for a character, or null — callers degrade, never block. */
export function clipFor(characterId: string, clipId: string, data: CharacterAnimsData = CHARACTER_ANIMS): CharacterClip | null {
  return data.characters[characterId]?.clips[clipId] ?? null;
}

/** Every staged clip of a character (empty object when it has none). */
export function clipsFor(characterId: string, data: CharacterAnimsData = CHARACTER_ANIMS): Record<string, CharacterClip> {
  return data.characters[characterId]?.clips ?? {};
}

/** Texture AND animation key for a staged clip — one namespace, one owner. */
export function clipKey(characterId: string, clipId: string): string {
  return `canim_${characterId}_${clipId}`;
}

/**
 * The clip character dressing a board dragon of this chain+tier, or null.
 * SKIN-AWARE: a purchased dragon (Emporium Frost/Storm) wears its own breed's
 * clip set; the bare chain falls back to the skinless character — and a skin
 * with no clip set of its own falls back the same way rather than to nothing.
 */
export function dragonClipCharacter(
  chain: string,
  tier: number,
  skin?: string | null,
  data: CharacterAnimsData = CHARACTER_ANIMS
): string | null {
  const key = `${chain}:${tier}`;
  let bare: string | null = null;
  for (const [id, c] of Object.entries(data.characters)) {
    if (c.board !== key) continue;
    if (skin && c.skin === skin) return id;
    if (!c.skin) bare = id;
  }
  return bare;
}

/** Characters whose clips dress board dragons — loaded at boot, not per world. */
export function boardClipCharacters(data: CharacterAnimsData = CHARACTER_ANIMS): string[] {
  return Object.entries(data.characters)
    .filter(([, c]) => c.board)
    .map(([id]) => id);
}

/**
 * The Phaser origin that puts the clip's bottom-centre at anchor + (dx, dy).
 * `flip` mirrors the registration for a right-facing play (source art faces
 * left, same single-flip convention the rigs use) — dx changes sign, so the
 * content lands where the mirrored rig's would.
 */
export function originFor(clip: CharacterClip, flip = false): { x: number; y: number } {
  const dx = flip ? -clip.dx : clip.dx;
  return {
    x: 0.5 - dx / (clip.frameWidth * clip.scale),
    y: 1 - clip.dy / (clip.frameHeight * clip.scale)
  };
}

/** The Phaser origin that puts the clip's bottom-centre at anchor + (dx, dy). */
export function clipOrigin(clip: CharacterClip): { x: number; y: number } {
  return originFor(clip, false);
}

/**
 * Map a rect given in GAME px relative to the anchor (e.g. the standee bank's
 * body box, pre-scaled) into the clip's TEXTURE space — hit areas are authored
 * in texture space so `setScale` cannot shift them.
 */
export function clipTextureRect(
  clip: CharacterClip,
  gameRect: { x: number; y: number; width: number; height: number }
): { x: number; y: number; width: number; height: number } {
  return {
    x: (gameRect.x - clip.dx) / clip.scale + clip.frameWidth / 2,
    y: (gameRect.y - clip.dy) / clip.scale + clip.frameHeight,
    width: gameRect.width / clip.scale,
    height: gameRect.height / clip.scale
  };
}

/**
 * Structural validation, run by the unit test against the committed file so a
 * broken push fails `pnpm verify` rather than mis-rendering a standee.
 */
export function validateCharacterAnims(data: CharacterAnimsData, maxTexture = 4096): string[] {
  const errors: string[] = [];
  if (data.version !== 1) errors.push(`version must be 1, got ${String(data.version)}`);
  for (const [id, c] of Object.entries(data.characters ?? {})) {
    for (const [clipId, clip] of Object.entries(c.clips ?? {})) {
      const at = `${id}/${clipId}`;
      if (typeof clip.file !== 'string' || !clip.file.startsWith('sprites/anims/')) {
        errors.push(`${at}: file must live under sprites/anims/`);
      }
      for (const k of ['frames', 'frameWidth', 'frameHeight', 'fps', 'scale'] as const) {
        if (!Number.isFinite(clip[k]) || (clip[k] as number) <= 0) errors.push(`${at}: ${k} must be > 0`);
      }
      for (const k of ['dx', 'dy'] as const) {
        if (!Number.isFinite(clip[k])) errors.push(`${at}: ${k} must be finite`);
      }
      if (typeof clip.loop !== 'boolean') errors.push(`${at}: loop must be boolean`);
      if (clip.stage !== undefined && clip.stage !== 'board' && clip.stage !== 'portrait') {
        errors.push(`${at}: stage must be 'board' or 'portrait'`);
      }
      for (const [seg, range] of Object.entries(clip.segments ?? {})) {
        if (
          !Array.isArray(range) ||
          range.length !== 2 ||
          !Number.isInteger(range[0]) ||
          !Number.isInteger(range[1]) ||
          range[0] < 0 ||
          range[1] <= range[0] ||
          range[1] > clip.frames
        ) {
          errors.push(`${at}: segment "${seg}" must be [start, endExclusive] inside 0..${clip.frames}`);
        }
      }
      if (clip.frameWidth > maxTexture || clip.frameHeight > maxTexture) {
        errors.push(`${at}: a single frame exceeds the ${maxTexture}px texture budget`);
      }
    }
  }
  return errors;
}
