/**
 * ZONES — a world made of several independently placed grids.
 *
 * The single-lattice world (`map.json` + the ambient projection in iso.ts) is one
 * diamond pitch covering everything. A zoned world is a set of `ZoneDef`s, each
 * with its OWN perspective, tile size, matrix, rotation and world-space origin,
 * so a floating island can carry a grid that matches its art rather than being
 * forced onto a global pitch. `src/data/worlds.json` (GENERATED by
 * `scripts/ingest-worlds.mjs`) is the registry.
 *
 * This module is the pure geometry: zone-local (i,j) ↔ world pixels. It is
 * Phaser-free and reads no ambient state, for the same reason `mapSpace` does not
 * — several zones are live at once, so a single module-level projection is not
 * merely inconvenient, it is wrong.
 *
 * A cell's identity is its WORLD POINT, never its (i,j). Two zones both have a
 * cell (0,0) and they are nowhere near each other; and the editor's own
 * `gameCell` projection onto one coarse lattice collapses 41% of the shipped
 * cells onto addresses another cell already holds. World pixels are the only
 * address that survives, which is exactly the rule `mapSpace.ts` states for
 * saved positions.
 */

export interface ZoneCell {
  /** Column within THIS zone. Meaningless outside it. */
  i: number;
  /** Row within THIS zone. */
  j: number;
  /** Cell centre in world pixels — the address that is actually unique. */
  x: number;
  y: number;
  /** Keeper level at which this cell becomes playable (1 = immediately). */
  unlock: number;
}

export interface ZoneDef {
  id: string;
  name: string;
  /** 'iso' = 2:1-style diamonds (the game look); 'ortho' = axis-aligned squares. */
  persp: 'iso' | 'ortho';
  /** One cell's full width/height in world px. */
  tile: { w: number; h: number };
  matrix: { cols: number; rows: number };
  /** Degrees about the footprint centre, normalised to (-180, 180]. */
  rotation: number;
  /** World position of cell (0,0)'s CENTRE, before rotation. */
  origin: { x: number; y: number };
  /** Footprint box in world px — also the pivot for `rotation`. */
  bounds: { x: number; y: number; w: number; h: number } | null;
  cells: ZoneCell[];
}

export interface WorldDef {
  id: string;
  name: string;
  /** The editor's "Level N" paging — the order worlds are meant to open in. */
  level: number;
  backdrop: string;
  primary: boolean;
  live: boolean;
  authoredDefault: boolean;
  zones: ZoneDef[];
  unlockOverrides: { cell: string; unlock: number }[];
}

export interface WorldsData {
  format: string;
  version: number;
  source: string;
  generatedBy: string;
  primary: string | null;
  teleport: {
    trigger: string;
    chain: string | null;
    tier: number | null;
    dragonChain: string | null;
    toWorld: string;
  } | null;
  worlds: WorldDef[];
}

/** Per-column (`u`) and per-row (`v`) step vectors, before rotation. */
export function zoneBasis(z: Pick<ZoneDef, 'persp' | 'tile'>): {
  u: { x: number; y: number };
  v: { x: number; y: number };
} {
  if (z.persp === 'ortho') return { u: { x: z.tile.w, y: 0 }, v: { x: 0, y: z.tile.h } };
  return { u: { x: z.tile.w / 2, y: z.tile.h / 2 }, v: { x: -z.tile.w / 2, y: z.tile.h / 2 } };
}

const rotateAround = (
  p: { x: number; y: number },
  c: { x: number; y: number },
  rad: number
): { x: number; y: number } => {
  if (!rad) return { x: p.x, y: p.y };
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  const dx = p.x - c.x;
  const dy = p.y - c.y;
  return { x: c.x + dx * cos - dy * sin, y: c.y + dx * sin + dy * cos };
};

/** Pivot for a zone's rotation: its footprint centre (falls back to the origin). */
export function zonePivot(z: ZoneDef): { x: number; y: number } {
  return z.bounds
    ? { x: z.bounds.x + z.bounds.w / 2, y: z.bounds.y + z.bounds.h / 2 }
    : { x: z.origin.x, y: z.origin.y };
}

/** Zone-local (i,j) → world pixel centre. */
export function zoneCellCenter(z: ZoneDef, i: number, j: number): { x: number; y: number } {
  const { u, v } = zoneBasis(z);
  const flat = { x: z.origin.x + i * u.x + j * v.x, y: z.origin.y + i * u.y + j * v.y };
  return rotateAround(flat, zonePivot(z), (z.rotation * Math.PI) / 180);
}

/** World pixel → the zone cell containing it, or null when outside this zone's
 *  matrix. Rotation is undone first, then the basis inverted. */
export function zoneCellAt(z: ZoneDef, x: number, y: number): { i: number; j: number } | null {
  const p = rotateAround({ x, y }, zonePivot(z), (-z.rotation * Math.PI) / 180);
  const { u, v } = zoneBasis(z);
  const det = u.x * v.y - v.x * u.y;
  if (!det) return null;
  const dx = p.x - z.origin.x;
  const dy = p.y - z.origin.y;
  // `|| 0` collapses NEGATIVE ZERO. Math.round(-0.2) is -0, which compares equal
  // to 0 but stringifies as "-0" — enough to make a "-0,3" cell key miss the
  // "0,3" it means, and to survive into JSON where it is a lasting trap.
  const i = Math.round((dx * v.y - v.x * dy) / det) || 0;
  const j = Math.round((u.x * dy - dx * u.y) / det) || 0;
  if (i < 0 || j < 0 || i >= z.matrix.cols || j >= z.matrix.rows) return null;
  return { i, j };
}

/**
 * Every playable cell of a world, flattened with the zone it came from.
 * Ordered by zone then cell, so it is stable across runs.
 */
export function worldCells(w: WorldDef): { zone: ZoneDef; cell: ZoneCell }[] {
  return w.zones.flatMap((zone) => zone.cells.map((cell) => ({ zone, cell })));
}

/** The world a save/teleport names, or undefined. */
export function worldById(data: WorldsData, id: string): WorldDef | undefined {
  return data.worlds.find((w) => w.id === id);
}
