#!/usr/bin/env node
/**
 * What does the RUNNING GAME actually fetch?
 *
 *   node scripts/audit-art.mjs            # report against dist/
 *   node scripts/audit-art.mjs --assets   # report against assets/ (pre-filter)
 *   node scripts/audit-art.mjs --json     # machine-readable
 *
 * `dist` is built by a FILTER (vite.config.ts `copyRuntimeArt`), and a filter can
 * only drop what someone thought to name. This walks the other way: it resolves
 * every asset path the runtime can ask for — from the data files and from the
 * loaders' own path grammars — and reports what ships that nothing references.
 *
 * The resolvers below mirror one loader each; when a loader's path grammar
 * changes, its resolver here has to change with it, so each one names its source.
 * Anything this script cannot see is a FALSE POSITIVE risk, so it reports
 * unreferenced files for a human to judge — it never deletes.
 */
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(path.join(root, rel), 'utf8');
const readJson = (rel) => JSON.parse(read(rel));

/** rel → why it is referenced (first reason wins; used for the report). */
const refs = new Map();
const ref = (p, why) => {
  if (!p) return;
  const clean = p.replace(/^\.?\//, '');
  if (!refs.has(clean)) refs.set(clean, why);
};

// 1. assets.json — every `source: "file"` entry. PreloadScene/lazyTextures load
//    `entry.file` verbatim, relative to the publicDir. A `placeholder` entry
//    names a file too, but TextureFactory paints that key at runtime and the
//    file is deliberately not shipped, so it is not part of the graph.
for (const e of readJson('src/data/assets.json').images ?? []) {
  if (e.source === 'file' && e.file) ref(e.file, `assets.json:${e.key}`);
}

// 2. Rigs — characterCatalog.ts `url:` fields and BoardScene's RIGS map. The
//    part images ride INSIDE the rig json as data URIs (RigPlayer reads
//    `rig.images`), so a rig folder's sibling PNGs are authoring copies.
for (const src of ['src/render/characterCatalog.ts', 'src/scenes/BoardScene.ts']) {
  for (const [, url] of read(src).matchAll(/'(sprites\/[^']*\.rig\.json)'/g)) ref(url, src);
}
// …and the layer files a rig would fall back to if its json ever ships unpacked.
for (const [rel] of refs) {
  if (!rel.endsWith('.rig.json')) continue;
  const abs = path.join(root, 'assets', rel);
  if (!existsSync(abs)) continue;
  const rig = JSON.parse(readFileSync(abs, 'utf8'));
  const embedded = rig.images ?? {};
  for (const layer of rig.layers ?? []) {
    if (!embedded[layer.file]) ref(`${path.dirname(rel)}/${layer.file}`, `${rel}:unpacked layer`);
  }
}

// 3. Dialogue sequences — sequenceCatalog.ts `builtinSequenceFiles`:
//    `${dir}/${i}.png` for `count` frames, plus the `endIdle` still.
const seqSrc = read('src/render/sequenceCatalog.ts');
// `dir` then an OPTIONAL `ext` then `count` — a bank re-encoded to lossless
// WebP by scripts/optimize-art.py declares its extension there.
for (const [, dir, ext, count] of seqSrc.matchAll(
  /dir:\s*'([^']+)',\s*\n(?:\s*ext:\s*'(\w+)',\s*\n)?\s*count:\s*(\d+)/g
)) {
  for (let i = 0; i < Number(count); i++) ref(`${dir}/${i}.${ext ?? 'png'}`, 'sequenceCatalog');
}
for (const [, still] of seqSrc.matchAll(/endIdle:\s*'([^']+)'/g)) ref(still, 'sequenceCatalog:endIdle');

// 4. Head blink/talk banks — faces.json (GENERATED by scripts/calibrate-faces.mjs);
//    faceAnimations resolves `${basePath}/${set.dir}/${frame.file}`.
for (const [who, face] of Object.entries(readJson('src/data/faces.json'))) {
  for (const set of Object.values(face.sets ?? {})) {
    for (const f of set.frames ?? []) ref(`${face.basePath}/${set.dir}/${f.file}`, `faces.json:${who}`);
  }
}

// 5. Portrait disc atlases — PreloadScene loads ONE sheet per ANIMATED_SPEAKER
//    (PortraitAnimator.ts), `sprites/${who}-merge/disc-atlas.png`. Note the
//    `-merge` suffix: the un-suffixed `sprites/<who>/` folder is the bake INPUT.
const speakers = read('src/entities/PortraitAnimator.ts').match(/ANIMATED_SPEAKERS\s*=\s*\[([^\]]*)\]/)?.[1] ?? '';
for (const [, who] of speakers.matchAll(/'([^']+)'/g)) {
  ref(`sprites/${who}-merge/disc-atlas.png`, 'PreloadScene:disc');
}

// 6. World standees — PreloadScene, `sprites/${id}/world-${bank}.webp` for every
//    id in STANDEE_BANKS.
for (const [, id] of read('src/core/Constants.ts').matchAll(/STANDEE_BANKS[\s\S]*?\n\};/g)[Symbol.iterator]
  ? read('src/core/Constants.ts')
      .match(/export const STANDEE_BANKS[\s\S]*?\n\};/)?.[0]
      .matchAll(/^\s{2}([a-z_]+):\s*\{/gm) ?? []
  : []) {
  ref(`sprites/${id}/world-idle.webp`, 'STANDEE_BANKS');
  ref(`sprites/${id}/world-cast.webp`, 'STANDEE_BANKS');
}

// 7. VFX bank — FlipbookFX/emitterAssets: the ramp LUT, the `_pack`/`_mv` pair of
//    every SHIPPED sheet, and the particle stills fx-emitters.json names.
ref('vfx-bank/ramps.png', 'vfxBank');
const shipped = read('src/render/vfxBank.ts').match(/export const SHIPPED\s*=\s*\[([^\]]*)\]/)?.[1] ?? '';
for (const [, key] of shipped.matchAll(/'([^']+)'/g)) {
  ref(`vfx-bank/flipbooks/${key}_pack.png`, 'vfxBank:SHIPPED');
  ref(`vfx-bank/flipbooks/${key}_mv.png`, 'vfxBank:SHIPPED');
}
for (const rel of Object.values(readJson('src/data/fx-emitters.json').textures ?? {})) {
  ref(`vfx-bank/${rel}`, 'fx-emitters.json');
}

// 7b. Looping music — AudioManager builds it off `import.meta.env.BASE_URL`.
for (const [, url] of read('src/audio/AudioManager.ts').matchAll(/BASE_URL\}([A-Za-z0-9_./-]+\.[a-z0-9]{2,5})`/g)) {
  ref(url, 'AudioManager');
}

// 8. Everything else spelled out as a literal anywhere in src/ or index.html —
//    the catch-all for one-off loads (music, backdrops, pointer art, map data).
const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name);
    if (statSync(abs).isDirectory()) walk(abs, out);
    else out.push(abs);
  }
  return out;
};
const LITERAL = /['"`]\/?((?:sprites|vfx-bank|background-music|map|atlases|raw)\/[A-Za-z0-9_./-]+\.[a-z0-9]{2,5})['"`]/g;
for (const abs of walk(path.join(root, 'src'))) {
  if (!/\.(ts|tsx|json)$/.test(abs)) continue;
  // assets.json is resolved properly above — scanning it as text would also
  // pick up the `placeholder` entries, whose files never ship by design.
  if (abs.endsWith(`${path.sep}data${path.sep}assets.json`)) continue;
  for (const [, p] of readFileSync(abs, 'utf8').matchAll(LITERAL)) {
    ref(p, path.relative(root, abs));
  }
}
for (const [, p] of read('index.html').matchAll(LITERAL)) ref(p, 'index.html');

// ── report ────────────────────────────────────────────────────────────────
const target = process.argv.includes('--assets') ? 'assets' : 'dist';
const base = path.join(root, target);
if (!existsSync(base)) {
  console.error(`[audit-art] no ${target}/ — run \`pnpm build\` first`);
  process.exit(1);
}
const shippedFiles = walk(base)
  .map((abs) => path.relative(base, abs).split(path.sep).join('/'))
  // Vite's own emit (bundle, entry html) is not art and is never in the graph.
  .filter((rel) => !/^assets\/index-[A-Za-z0-9_-]+\.(js|css)$/.test(rel) && rel !== 'index.html');
const unref = [];
let refBytes = 0;
let unrefBytes = 0;
for (const rel of shippedFiles) {
  const size = statSync(path.join(base, rel)).size;
  if (refs.has(rel)) refBytes += size;
  else {
    unrefBytes += size;
    unref.push({ rel, size });
  }
}
unref.sort((a, b) => b.size - a.size);

/**
 * Deliberately absent, and not a finding:
 *  · a speaker with a disc atlas ships the atlas, not the frames it was baked
 *    from — those remain in `assets/` for the UI Builder, which runs off the dev
 *    server (the same rule vite.config.ts applies on the way into dist);
 *  · the two guides' `rest.png` stills, for the same reason.
 */
const atlasSpeakers = (
  read('src/entities/PortraitAnimator.ts').match(/ANIMATED_SPEAKERS\s*=\s*\[([^\]]*)\]/)?.[1] ?? ''
)
  .split(',')
  .map((x) => x.trim().replace(/^'|'$/g, ''))
  .filter(Boolean);
const editorOnly = (rel) => atlasSpeakers.some((who) => rel.startsWith(`sprites/${who}-merge/`));
const missing = [...refs.keys()].filter((r) => !shippedFiles.includes(r) && !editorOnly(r));

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ target, refBytes, unrefBytes, unref, missing }, null, 2));
} else {
  const mb = (n) => `${(n / 1048576).toFixed(1)} MB`;
  console.log(`[audit-art] ${target}/ — ${shippedFiles.length} files`);
  console.log(`  referenced   ${String(shippedFiles.length - unref.length).padStart(5)}  ${mb(refBytes)}`);
  console.log(`  UNreferenced ${String(unref.length).padStart(5)}  ${mb(unrefBytes)}`);
  const byDir = new Map();
  for (const u of unref) {
    const d = path.dirname(u.rel);
    const cur = byDir.get(d) ?? { n: 0, size: 0 };
    byDir.set(d, { n: cur.n + 1, size: cur.size + u.size });
  }
  console.log('\n  unreferenced, by directory:');
  for (const [d, v] of [...byDir].sort((a, b) => b[1].size - a[1].size).slice(0, 30)) {
    console.log(`    ${mb(v.size).padStart(9)}  ${String(v.n).padStart(4)}  ${d}`);
  }
  if (missing.length) {
    console.log(`\n  referenced but NOT shipped (${missing.length}) — loader falls back:`);
    for (const m of missing.slice(0, 20)) console.log(`    ${m}   (${refs.get(m)})`);
    if (missing.length > 20) console.log(`    …and ${missing.length - 20} more`);
  }
}
