#!/usr/bin/env python3
"""
Pack the baked crystal frames into one sprite sheet.

## What may and may not change

The sheet has to be a DROP-IN for the 803x902 canvas texture it replaces, so the
packer only ever does things that leave the gem's pixels where they were:

  * horizontal trim is SYMMETRIC about the canvas centre, so `anchors.json`'s
    x = 0.5 still points at the spin axis;
  * vertical trim is compensated exactly in the anchor (the packer prints the
    new y), because 0.92 of a shorter frame is not the same place;
  * a `--scale` below 1 rescales the pixels, so it is the one option that needs
    `ITEM_SCALE.crystal_1` raised by 1/scale. The packer prints that too.

Margins carry no ink, so trimming them cannot change what is drawn — only the
sprite's bounds, and with them the art hit rect (tighter, and transparent pixels
already yielded the hit) and anything derived from `displayWidth`.

    python3 scripts/pack-crystal.py --frames-dir DIR [--measure] [--scale 1.0]
                                    [--max-dim 4096]
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT_IMG = ROOT / "assets/sprites/items/crystal-spin.webp"
OUT_META = ROOT / "src/data/crystal-spin.json"

# The anchor the live texture is calibrated with (src/data/anchors.json).
ANCHOR_Y = 0.92
ITEM_SCALE_CRYSTAL_1 = 0.4


def alpha_bbox(im: Image.Image):
    return im.getchannel("A").getbbox()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames-dir", required=True)
    ap.add_argument("--measure", action="store_true", help="report the silhouette, write nothing")
    ap.add_argument("--scale", type=float, default=1.0)
    ap.add_argument("--max-dim", type=int, default=4096)
    ap.add_argument("--quality", type=int, default=92)
    args, _ = ap.parse_known_args()

    paths = sorted(Path(args.frames_dir).glob("*.png"))
    if not paths:
        raise SystemExit("pack-crystal: no frames found")
    frames = [Image.open(p).convert("RGBA") for p in paths]
    src_w, src_h = frames[0].size

    boxes = [alpha_bbox(f) for f in frames]
    left = min(b[0] for b in boxes)
    top = min(b[1] for b in boxes)
    right = max(b[2] for b in boxes)
    bottom = max(b[3] for b in boxes)
    # Symmetric about the centre so the spin axis stays at x = 0.5.
    m = min(left, src_w - right)
    cut = (m, top, src_w - m, bottom)
    cw, ch = cut[2] - cut[0], cut[3] - cut[1]

    print(f"[pack-crystal] {len(frames)} frames of {src_w}x{src_h}")
    print(f"[pack-crystal] union ink box  L{left} T{top} R{right} B{bottom}")
    print(f"[pack-crystal] symmetric cut  {cw}x{ch}  ({cw * ch / (src_w * src_h):.0%} of the canvas)")

    # Best grid: the one that fits max-dim with the least wasted atlas area.
    cell_w = max(1, round(cw * args.scale))
    cell_h = max(1, round(ch * args.scale))
    best = None
    for cols in range(1, len(frames) + 1):
        rows = math.ceil(len(frames) / cols)
        w, h = cols * cell_w, rows * cell_h
        if w > args.max_dim or h > args.max_dim:
            continue
        if best is None or w * h < best[2] * best[3]:
            best = (cols, rows, w, h)
    if best is None:
        raise SystemExit(
            f"pack-crystal: {len(frames)} cells of {cell_w}x{cell_h} cannot fit "
            f"{args.max_dim}x{args.max_dim} — lower --scale"
        )
    cols, rows, atlas_w, atlas_h = best
    print(
        f"[pack-crystal] scale {args.scale:g} → cell {cell_w}x{cell_h}, "
        f"grid {cols}x{rows}, atlas {atlas_w}x{atlas_h} "
        f"({atlas_w * atlas_h * 4 / 1e6:.0f} MB uncompressed)"
    )

    # The anchor moves only by the vertical trim; x is untouched by construction.
    anchor_y = (ANCHOR_Y * src_h - cut[1]) / ch
    item_scale = ITEM_SCALE_CRYSTAL_1 / args.scale
    print(f"[pack-crystal] anchor y {ANCHOR_Y} → {anchor_y:.4f}")
    print(f"[pack-crystal] ITEM_SCALE.crystal_1 {ITEM_SCALE_CRYSTAL_1} → {item_scale:.6g}")

    if args.measure:
        return 0

    sheet = Image.new("RGBA", (atlas_w, atlas_h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        cell = f.crop(cut)
        if (cell_w, cell_h) != (cw, ch):
            cell = cell.resize((cell_w, cell_h), Image.LANCZOS)
        sheet.paste(cell, ((i % cols) * cell_w, (i // cols) * cell_h))

    OUT_IMG.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(OUT_IMG, "WEBP", quality=args.quality, method=6)
    meta = {
        "note": "GENERATED by scripts/bake-crystal.mjs — do not hand-edit.",
        "frameWidth": cell_w,
        "frameHeight": cell_h,
        "frames": len(frames),
        "columns": cols,
        "rows": rows,
        "periodMs": 1800,
        "anchor": [0.5, round(anchor_y, 4)],
        "itemScale": round(item_scale, 6),
        "sourceSize": [src_w, src_h],
    }
    OUT_META.write_text(json.dumps(meta, indent=2) + "\n")
    print(
        f"[pack-crystal] wrote {OUT_IMG.relative_to(ROOT)} "
        f"({OUT_IMG.stat().st_size / 1e6:.2f} MB) + {OUT_META.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
