import { existsSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import charactersDoc from '../../src/data/characters.json';
import { ZONES } from '../../src/core/world';
import {
  CHARACTER_ANIMS,
  clipFor,
  clipOrigin,
  clipTextureRect,
  validateCharacterAnims,
  type CharacterClip
} from '../../src/core/characterAnims';

const ROOT = path.resolve(__dirname, '../..');

/**
 * character-anims.json is GENERATED by the Align Studio push
 * (scripts/apply-anim-align.mjs, /__animalign) — these are the properties a
 * push must never break. A clip that names a missing sheet would fail as a
 * loader 404 in a world the e2e tutorial never visits; a frame past the 4096
 * texture ceiling would fail only on the old devices the budget exists for.
 */
describe('character-anims.json', () => {
  it('validates structurally (finite transforms, staged paths, texture budget)', () => {
    expect(validateCharacterAnims(CHARACTER_ANIMS)).toEqual([]);
  });

  it('every staged sheet actually exists under assets/', () => {
    for (const [id, c] of Object.entries(CHARACTER_ANIMS.characters)) {
      for (const [clipId, clip] of Object.entries(c.clips)) {
        expect(existsSync(path.join(ROOT, 'assets', clip.file)), `${id}/${clipId}: ${clip.file}`).toBe(true);
      }
    }
  });

  it('world characters with an idle clip are known wardrobe keys', () => {
    // The runtime looks clips up by `art ?? id` — an alignment pushed under a
    // name no character wears can never be shown and is almost certainly a typo.
    const wardrobe = new Set(
      (charactersDoc as { characters: { id: string; art?: string }[] }).characters.map((c) => c.art ?? c.id)
    );
    // A DECOR clip set is named after a map-decor piece rather than a person
    // (Runevault's `cauldron`), so it is held to the same rule against a
    // different roster — a clip under a name nothing on any map places is just
    // as unshowable as one under a name nobody wears.
    const props = new Set(
      ZONES.worlds.flatMap((w) => (w.map.mapDecor ?? []).map((d) => d.name))
    );
    for (const [id, c] of Object.entries(CHARACTER_ANIMS.characters)) {
      if (c.board) continue; // board dragons (redwhelp, redadult…), not world characters
      if (Object.values(c.clips).every((clip) => clip.stage === 'decor')) {
        expect(props.has(id), `${id} is not placed as map decor by any world`).toBe(true);
        continue;
      }
      expect(wardrobe.has(id), `${id} is not worn by anyone in characters.json`).toBe(true);
    }
  });
});

describe('clip transform maths', () => {
  const clip: CharacterClip = {
    file: 'sprites/anims/eleanor/idle.webp',
    frames: 60,
    frameWidth: 200,
    frameHeight: 320,
    fps: 12,
    loop: true,
    scale: 0.5,
    dx: 10,
    dy: -20
  };

  it('clipOrigin puts the frame bottom-centre at anchor + (dx, dy)', () => {
    const o = clipOrigin(clip);
    // world x of texture point p: anchor + (p - origin*w)*scale — at p = w/2
    // that must equal anchor + dx
    expect((clip.frameWidth / 2 - o.x * clip.frameWidth) * clip.scale).toBeCloseTo(clip.dx, 6);
    expect((clip.frameHeight - o.y * clip.frameHeight) * clip.scale).toBeCloseTo(clip.dy, 6);
  });

  it('clipTextureRect round-trips through the draw convention', () => {
    const game = { x: -30, y: -120, width: 60, height: 100 };
    const tex = clipTextureRect(clip, game);
    // map the texture rect back to game space via the same convention
    expect((tex.x - clip.frameWidth / 2) * clip.scale + clip.dx).toBeCloseTo(game.x, 6);
    expect((tex.y - clip.frameHeight) * clip.scale + clip.dy).toBeCloseTo(game.y, 6);
    expect(tex.width * clip.scale).toBeCloseTo(game.width, 6);
    expect(tex.height * clip.scale).toBeCloseTo(game.height, 6);
  });

  it('clipFor degrades to null, never throws', () => {
    expect(clipFor('nobody', 'idle')).toBeNull();
    expect(clipFor('eleanor', 'no_such_clip')).toBeNull();
  });
});
